// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsJ2K-Y3L07AnWRvHPP7mVAX8MIQEIhrw',
    appId: '1:316459256562:web:749ebe0ff0b65354ab5e6b',
    messagingSenderId: '316459256562',
    projectId: 'baduylearn',
    authDomain: 'baduylearn.firebaseapp.com',
    databaseURL: 'https://baduylearn-default-rtdb.firebaseio.com',
    storageBucket: 'baduylearn.firebasestorage.app',
    measurementId: 'G-T913D5DYXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcxUatBPVxzZhJvzJyA9fomNgxHwPEKXo',
    appId: '1:316459256562:android:338762130c04a05cab5e6b',
    messagingSenderId: '316459256562',
    projectId: 'baduylearn',
    databaseURL: 'https://baduylearn-default-rtdb.firebaseio.com',
    storageBucket: 'baduylearn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDge8Ig6g_bu0SdmljDC2wNoIP7MCumQv8',
    appId: '1:316459256562:ios:b994b9b512fa2431ab5e6b',
    messagingSenderId: '316459256562',
    projectId: 'baduylearn',
    databaseURL: 'https://baduylearn-default-rtdb.firebaseio.com',
    storageBucket: 'baduylearn.firebasestorage.app',
    iosBundleId: 'com.example.baduylearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDge8Ig6g_bu0SdmljDC2wNoIP7MCumQv8',
    appId: '1:316459256562:ios:b994b9b512fa2431ab5e6b',
    messagingSenderId: '316459256562',
    projectId: 'baduylearn',
    databaseURL: 'https://baduylearn-default-rtdb.firebaseio.com',
    storageBucket: 'baduylearn.firebasestorage.app',
    iosBundleId: 'com.example.baduylearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsJ2K-Y3L07AnWRvHPP7mVAX8MIQEIhrw',
    appId: '1:316459256562:web:c227baf342005034ab5e6b',
    messagingSenderId: '316459256562',
    projectId: 'baduylearn',
    authDomain: 'baduylearn.firebaseapp.com',
    databaseURL: 'https://baduylearn-default-rtdb.firebaseio.com',
    storageBucket: 'baduylearn.firebasestorage.app',
    measurementId: 'G-7CD9B9ZTMB',
  );

}